# Generated by Django 3.1.7 on 2021-03-18 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dodsbo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Favorite',
            field=models.ManyToManyField(blank=True, default=None, related_name='Ønsket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.CharField(choices=[('Ønsket', 'Ønsket'), ('Angre ønsket', 'Angre ønsket')], default='Ønsket', max_length=50)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dodsbo.item')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
