# Generated by Django 3.1.6 on 2021-02-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodsbo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Beskrivelse mangler'),
        ),
    ]
