# Generated by Django 3.1.6 on 2021-02-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodsbo', '0002_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='wish',
        ),
        migrations.AddField(
            model_name='wish',
            name='discard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='donate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
