# Generated by Django 3.1.6 on 2021-02-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dodsbo', '0003_auto_20210218_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='estateID',
        ),
    ]
