# Generated by Django 3.1.6 on 2021-02-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dodsbo', '0004_remove_estate_estateid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='itemID',
        ),
        migrations.RemoveField(
            model_name='item',
            name='owner_username',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
    ]
